### ISSUE TITLE
work with catalogs.

### ISSUE THREAD

**Issue by ihsinme** [DigitalHERMES/jnos2#1]
Good afternoon.
I want to draw your attention to a possible error in your code.
you are using chroot without setting a working directory.
https://github.com/DigitalHERMES/jnos2/blob/0530887762a1bc3492b4b42c81a01d592b42b31a/files.c#L410

this problem is well described here https://cwe.mitre.org/data/definitions/243.html.

I suggest adding a challenge.

**Comment by rafael2k** [comment]
Please report to upstream.
